# Site settings
title: Builder
header-img: img/home-bg.jpg
email: antonio.oliverio@gmail.com
copyright_name: Antonio Oliverio
description: "CakePHP 3.x plugin to generate beautiful & functional crud GUI in Bootstrap 3 style!"
baseurl: "/builder"
url: "https://aoliverio.github.io"
twitter_username: aoliverio
github_username: aoliverio
facebook_username: antonio.oliverio
email_username:
    
# GetLatest
getlatest_url: "https://github.com/aoliverio/builder/releases"
getlatest_label: "GET LATEST RELEASE"
    
# GitHub
github:
    code_url: "https://github.com/aoliverio/builder"
    pulls_url: "https://github.com/aoliverio/builder/pulls"
    issues_url: "https://github.com/aoliverio/builder/issues"
    releases_url: "https://github.com/aoliverio/builder/releases"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 3
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Gems
gems: [jekyll-paginate, jekyll-feed]
