# Site settings
title: Builder for CakePHP
header-img: img/home-bg.jpg
email: antonio.oliverio@gmail.com
copyright_name: aoliverio.com
description: "CakePHP 3.x plugin to generate beautiful & functional crud GUI in Bootstrap 3 style!"
baseurl: "/builder"
url: "https://aoliverio.github.io"
twitter_username: aoliverio
github_username:  aoliverio
facebook_username:  antonio.oliverio
email_username:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
